---
title: "SSECR Module: Data Wrangling"
description: "Data wrangling and harmonization for synthesis projects"
author: "LTER"
categories: [LTER, module, website, data-harmonization, data-wrangling, data-qc, code-conditionals, joins, data-shape, loops, custom-r-functions]
---

## Materials

<br>

::: {.center-text .body-text-l}
[{{< fa window-maximize title="a web browser" >}} course website](https://lter.github.io/ssecr/mod_wrangle.html){target="_blank"} & [{{< fa brands github title="The GitHub octocat icon" >}} source code](https://github.com/lter/ssecr){target="_blank"}
:::

## Abstract

Now that we have covered how to find data and use data visualization methods to explore it, we can move on to combining separate data files and preparing that combined data file for analysis. For the purposes of this module we're adopting a very narrow view of harmonization and a very broad view of wrangling but this distinction aligns well with two discrete philosophical/practical arenas. To make those definitions explicit:

- <u>"Harmonization" = process of combining separate primary data objects into one object</u>. This includes things like synonymizing columns, or changing data format to support combination. This _excludes_ quality control steps--even those that are undertaken before harmonization begins.

- <u>"Wrangling" = all modifications to data meant to create an analysis-ready 'tidy' data object</u>. This includes quality control, unit conversions, and data 'shape' changes to name a few. Note that attaching ancillary data to your primary data object (e.g., attaching temperature data to a dataset on plant species composition) _also falls into this category!_
