---
title: "SSECR Module: Reproducibility"
description: "Reproducibility in synthesis science projects"
author: "LTER"
categories: [LTER, module, website, reproducibility]
---

## Materials

<br>

::: {.center-text .body-text-l}
[{{< fa window-maximize title="a web browser" >}} course website](https://lter.github.io/ssecr/mod_reproducibility.html){target="_blank"} & [{{< fa brands github title="The GitHub octocat icon" >}} source code](https://github.com/lter/ssecr){target="_blank"}
:::

## Abstract

As we set out to engage with the synthesis skills this course aims to offer, it will be helpful to begin with a careful consideration of “reproducibility.” Because synthesis projects draw data from many sources and typically involve many researchers working in concert, reproducibility is particularly important. In individual projects, adhering to reproducibility best practices is certainly a good goal but failing to do so for synthesis projects can severely limit the work in a more significant way than for those individual projects. “Reproducibility” is a wide sphere encompassing many different–albeit related–topics so it can be challenging to feel well-equipped to evaluate how well we are following these guidelines in our own work. In this module, we will cover a few fundamental facets of reproducibility and point to some considerations that may encourage you to push yourself to elevate your practices to the next level.
